### ISSUE TITLE
no readme, unsure how to use this project

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/ern-base-composite-starter#1]
# problem

in efforts to expand my ern-fu, i came across this project, but:

- dont know what it is
- dont know how to use it

due to lack of common docs (e.g. `readme.md`, `contributing.md`)

**Comment by belemaire** [comment]
@cdaringe 
Sorry about that. It is actually documented in Electrode Native documentation. 
Added a light [README.md](./README.md) to link to the doc.

**Comment by cdaringe** [comment]
@belemaire, thanks mate.
